(**
   Typechecking of patterns
   @see <https://github.com/regnat/tix-papers> for the theory
*)

(** [infer p] returns the couple [(Γ, p')] where [Γ] is the new environment
   generated by this pattern and [p'] the pattern annotated with type
   informations *)
val infer : Nix_light.Ast.pattern -> (Typing_env.t * Typed_ast.pattern)
